name: adwaita
description: Adwaita style - The default theme for GTK+ for your Flutter app.
version: 1.1.0
homepage: https://github.com/gtk-flutter/adwaita

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^4.0.0

flutter:
